export const CHANGE_SLIDER_COLOR = "CHANGE_SLIDER_COLOR";
export const CHANGE_SLIDER_BACKGROUND_COLOR = "CHANGE_SLIDER_BACKGROUND_COLOR";
export const SET_COLOR_RED = "SET_COLOR_REDR";
export const SET_COLOR_GREEN = "SET_COLOR_GREEN";
export const SET_COLOR_BLUE = "SET_COLOR_BLUE";
export const SET_BACK_COLOR_RED = "SET_BACK_COLOR_RED";
export const SET_BACK_COLOR_GREEN = "SET_BACK_COLOR_GREEN";
export const SET_BACK_COLOR_BLUE = "SET_BACK_COLOR_BLUE";
